//! v0.3.0: 2025 client uses 2025Patch (native DLL injection) instead of BepInEx.
//!
//! This module keeps the public interface the launcher and defender expect
//! (`verify_for_launcher` / `repair_for_launcher` / `sync_plugin_from_mirror`)
//! but operates on the 2025Patch files (`2025Patch.dll`, `Injector.exe`,
//! `2025patch.ini`) instead of the BepInEx layout. There is no BepInEx and no
//! RecNetPlugin in the 2025 client — the patch DLL does the host rewriting
//! natively.

use std::path::Path;

/// 2025Patch files that must exist next to `Recroom_Release.exe`.
const PATCH_FILES: &[&str] = &["2025Patch.dll", "Injector.exe", "2025patch.ini"];

/// Quick 2025Patch health check for the launcher (`--play`).
/// Returns Ok when the patch can boot, Err(reason) when it needs repair.
pub fn verify_for_launcher(game_dir: &Path) -> Result<(), String> {
    for f in PATCH_FILES {
        if !game_dir.join(f).is_file() {
            return Err(format!("missing {f}"));
        }
    }
    Ok(())
}

/// Repair a broken 2025Patch install from the launcher: re-downloads the
/// patch zip and reinstalls it in place (with rollback).
pub async fn repair_for_launcher(
    client: &reqwest::Client,
    game_dir: &Path,
    ns_host: &str,
    _photon_rt: &str,
    _photon_voice: &str,
    _photon_chat: &str,
    progress: &crate::progress::Progress,
) -> Result<(), String> {
    let patch_zip = crate::fetch_patch2025_zip(client, progress).await?;
    let mut backups = crate::transaction::BackupSet::new();
    // Protect the existing patch files so a failed reinstall rolls back.
    for f in PATCH_FILES {
        let _ = backups.protect(&game_dir.join(f));
    }
    let res = crate::install_patch2025(game_dir, &patch_zip, ns_host, progress);
    let _ = std::fs::remove_file(&patch_zip);
    match res {
        Ok(()) => {
            backups.commit();
            Ok(())
        }
        Err(e) => {
            backups.rollback();
            Err(e)
        }
    }
}

/// 2025Patch auto-update: force-installs the embedded fixed patch files
/// (2025Patch.dll with jsonfix, Injector.exe, and 2025patch.ini) on every
/// --play. This ensures the client gets the clothing tab fix via the
/// installer's auto-update mechanism, even if the files were deleted or
/// corrupted.
pub async fn sync_plugin_from_mirror(
    game_dir: &Path,
    _progress: &crate::progress::Progress,
) {
    // Embedded fixed files (2025Patch.dll is the wrapper with jsonfix)
    const FIXED_DLL: &[u8] = include_bytes!("../assets/2025Patch.dll");
    const INJECTOR: &[u8] = include_bytes!("../assets/Injector.exe");

    // 1. Backup original DLL as 2025Patch-orig.dll (if not already done)
    let dest_dll = game_dir.join("2025Patch.dll");
    let orig_dll = game_dir.join("2025Patch-orig.dll");
    if !orig_dll.exists() {
        if let Ok(existing) = std::fs::read(&dest_dll) {
            // Only backup if it's the old 66KB version, not the 338KB wrapper
            if existing.len() < 100000 {
                let _ = std::fs::write(&orig_dll, &existing);
                println!("[2025Patch] backed up original as 2025Patch-orig.dll");
            }
        }
    }

    // 2. Force-write the fixed DLL (always overwrite to ensure correct version)
    match std::fs::write(&dest_dll, FIXED_DLL) {
        Ok(_) => println!("[2025Patch] installed fixed 2025Patch.dll ({} bytes, clothing tab fix)", FIXED_DLL.len()),
        Err(e) => eprintln!("[2025Patch] failed to write DLL: {}", e),
    }

    // 3. Ensure Injector.exe exists
    let injector = game_dir.join("Injector.exe");
    if !injector.exists() {
        if let Err(e) = std::fs::write(&injector, INJECTOR) {
            eprintln!("[2025Patch] failed to write Injector.exe: {}", e);
        } else {
            println!("[2025Patch] installed Injector.exe");
        }
    }

    // 4. Ensure 2025patch.ini exists with correct ApiHost
    let ini = game_dir.join("2025patch.ini");
    if !ini.exists() {
        // ApiHost is baked in at compile time via env var, fallback to fluxrec-api
        let ns_host = option_env!("FLUXREC_NS_HOST").unwrap_or("fluxrec-api.ripo-ripoteam.workers.dev");
        let ini_content = format!(
            "; Flux Rec 2025 patch configuration\n\
             ; Auto-generated by Flux Rec installer\n\
             \n\
             [config]\n\
             ApiHost={}\n\
             PhotonHost=\n\
             PhotonPort=0\n\
             EnableConsole=false\n\
             BlockDeadHosts=true\n\
             SuppressDuidMismatch=true\n\
             EnableTracing=false\n\
             VoiceKeyXml=\n",
            ns_host
        );
        if let Err(e) = std::fs::write(&ini, ini_content) {
            eprintln!("[2025Patch] failed to write 2025patch.ini: {}", e);
        } else {
            println!("[2025Patch] created 2025patch.ini (ApiHost={})", ns_host);
        }
    }
}
