-- SocialOrientation: the public multiplayer room the 2025 client's orientation
-- flow looks up (`GET /rooms?name=SocialOrientation`) when the player hits
-- "Go Now!". Room 46 + subroom 70 (reuses the Orientation scene, which the
-- client has locally). Public (Accessibility 1), up to 12 players.
-- INSERT OR IGNORE so this is safe to apply on databases that already have it.

INSERT OR IGNORE INTO room (data, visits) VALUES ('{"RoomId":46,"Name":"SocialOrientation","Description":"Meet new friends and explore Flux Rec together!","ImageName":"Orientation.jpg","WarningMask":0,"CustomWarning":null,"CreatorAccountId":1,"State":0,"Accessibility":1,"PublishState":0,"SupportsLevelVoting":false,"IsRRO":true,"IsRecRoomApproved":false,"ExcludeFromLists":false,"ExcludeFromSearch":false,"SupportsScreens":true,"SupportsWalkVR":true,"SupportsTeleportVR":true,"SupportsVRLow":true,"SupportsQuest2":true,"SupportsMobile":true,"SupportsJuniors":true,"MinLevel":0,"AgeRating":2,"CreatedAt":"2026-10-10T14:30:00.000000Z","PublishedAt":"2026-10-10T14:30:00.000000Z","BecameRRStudioRoomAt":null,"Stats":{"CheerCount":0,"FavoriteCount":0,"VisitorCount":0,"VisitCount":0},"RankingContext":null,"IsDorm":false,"IsPlacePlay":false,"MaxPlayerCalculationMode":0,"MaxPlayers":12,"CloningAllowed":false,"DisableMicAutoMute":false,"DisableRoomComments":true,"EncryptVoiceChat":false,"ToxmodEnabled":true,"LoadScreenLocked":false,"UgcVersion":1,"PersistenceVersion":0,"UgcSubVersion":null,"MinUgcSubVersion":null,"AutoLocalizeRoom":false,"LocalizationContext":{"TargetLocale":null,"Scope":null,"LocalizedFields":["Description","CustomWarning"]},"IsDeveloperOwned":true,"RankedEntityId":"46","Roles":[{"AccountId":1,"Role":255,"LastChangedByAccountId":null,"InvitedRole":0},{"AccountId":2,"Role":30,"LastChangedByAccountId":null,"InvitedRole":0},{"AccountId":28,"Role":255,"LastChangedByAccountId":null,"InvitedRole":0}],"IsJuniorCreated":false,"PromoImages":[],"PromoExternalContent":[],"LoadScreens":[],"RestrictedCircuitsAllowListNames":[],"SubRooms":[]}', 0);
INSERT OR IGNORE INTO subroom (sub_room_id, room_id, data) VALUES (70, 46, '{"SubRoomId":70,"RoomId":46,"CreatorAccountId":null,"UnitySceneId":"c79709d8-a31b-48aa-9eb8-cc31ba9505e8","Name":"Home","LastModeratedSaveModerationState":0,"IsSandbox":false,"MaxPlayers":12,"Accessibility":1,"ShouldAutoStageSaves":true}');
INSERT OR IGNORE INTO room_tag (room_id, tag, type, is_primary_genre) VALUES (46, 'rro', 2, 0);

-- Orientation itself is now a 12-player public room (matches ImportRooms.json).
UPDATE room SET data = '{"RoomId":13,"Name":"Orientation","Description":"An introductory tour of Flux Rec!","ImageName":"Orientation.jpg","WarningMask":0,"CustomWarning":null,"CreatorAccountId":1,"State":0,"Accessibility":1,"PublishState":0,"SupportsLevelVoting":false,"IsRRO":true,"IsRecRoomApproved":false,"ExcludeFromLists":false,"ExcludeFromSearch":false,"SupportsScreens":true,"SupportsWalkVR":true,"SupportsTeleportVR":true,"SupportsVRLow":true,"SupportsQuest2":true,"SupportsMobile":true,"SupportsJuniors":true,"MinLevel":0,"AgeRating":2,"CreatedAt":"2026-03-11T06:48:51.323621Z","PublishedAt":"2026-03-11T06:48:51.323621Z","BecameRRStudioRoomAt":null,"Stats":{"CheerCount":0,"FavoriteCount":0,"VisitorCount":0,"VisitCount":0},"RankingContext":null,"IsDorm":false,"IsPlacePlay":false,"MaxPlayerCalculationMode":0,"MaxPlayers":12,"CloningAllowed":false,"DisableMicAutoMute":false,"DisableRoomComments":true,"EncryptVoiceChat":false,"ToxmodEnabled":true,"LoadScreenLocked":false,"UgcVersion":1,"PersistenceVersion":0,"UgcSubVersion":null,"MinUgcSubVersion":null,"AutoLocalizeRoom":false,"LocalizationContext":{"TargetLocale":null,"Scope":null,"LocalizedFields":["Description","CustomWarning"]},"IsDeveloperOwned":true,"RankedEntityId":"13","Roles":[{"AccountId":1,"Role":255,"LastChangedByAccountId":null,"InvitedRole":0},{"AccountId":2,"Role":30,"LastChangedByAccountId":null,"InvitedRole":0},{"AccountId":28,"Role":255,"LastChangedByAccountId":null,"InvitedRole":0}],"IsJuniorCreated":false,"PromoImages":[],"PromoExternalContent":[],"LoadScreens":[],"RestrictedCircuitsAllowListNames":[]}' WHERE room_id = 13;
