<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>PlayButtonFix</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RestoreAdditionalProjectSources>
        https://api.nuget.org/v3/index.json;
        https://nuget.bepinex.dev/v3/index.json;
        https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PlayButtonFixPlugin.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>refs\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>refs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>refs\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>refs\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
