<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>PlayButtonFix</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <RestoreAdditionalProjectSources>
        https://api.nuget.org/v3/index.json;
        https://nuget.bepinex.dev/v3/index.json;
        https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="PlayButtonFixPlugin.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="UnityEngine.CoreModule" Version="2020.3.1" />
    <PackageReference Include="Unity3D.UnityEngine.UI" Version="2018.3.5.1" />
  </ItemGroup>
</Project>
