import 'zx/globals'

import { writeFileSync } from 'node:fs'
import { Command } from '@commander-js/extra-typings'
import Table from 'cli-table3'

import {
	buildCatalogLoad,
	CATALOG_INSERT_COLUMNS,
	CatalogKind,
	existedByLegacyBuild,
	isSellableRarity,
	LEGACY_CLIENT_BUILD,
	LEGACY_CLIENT_BUILD_DATE,
	priceForRarity,
	subscriberPriceFor,
} from '../../../../apps/econ/src/catalog-load'
import { getRepoRoot } from '../path'
import { readCaptures } from './catalog.cmd'

/**
 * Generate the two general-store catalogues the econ worker serves, both from the item catalog.
 *
 *     runx storefront build
 *
 * They are the same store at two points in time, and the econ worker picks which file a caller
 * gets from their token's `rn.ver`:
 *
 *   sf3.json       items that existed by LEGACY_CLIENT_BUILD — what the 2023 client is served
 *   sf3-2025.json  every sellable item — what a later build is served
 *
 * ONE storefront id either way. The client asks for 3 in both cases and neither knows there are
 * two files, so nothing about the request changes and no item is renumbered.
 *
 * Both are static catalogues like every other `sf{N}.json`, because that is the only shape
 * `loadStorefront` reads and because browse and BUY have to agree: `findStoreItem` resolves a
 * purchase against the very same file, so an item that is not in it cannot be bought.
 *
 * `sf3.json` used to be a CAPTURE of the real 2023 store and is now generated. What survives of
 * that capture is `static/db/consumables.json`: the 35 store items the item catalog does not
 * model as sellable entries. Everything else was dropped for a reason —
 *
 *   avatar items      the catalog has them, and generating keeps ONE source of truth for an
 *                     item's id and price
 *   equipment skins   not sold at all: they are awarded from weekly challenges, so a store
 *                     listing one would sell something the game gives away
 */

const OUT_DIR = 'apps/econ/static/storefronts'

/**
 * The store items the item catalog does not model, kept from the 2023 capture and copied into
 * both files verbatim — ids, prices and gift-drops untouched.
 *
 * 30 consumables and the 5 random boxes. Nothing here carries an `AvatarItemDesc` (the catalog
 * generates those) or an `EquipmentModificationGuid` (skins are awarded, not sold) — which is
 * exactly what qualified the rest for removal.
 */
const CARRIED_ITEMS = 'apps/econ/static/db/consumables.json'

/** RecCenterTokens — the currency the avatar storefronts sell in. */
const CURRENCY_TYPE_TOKENS = 2

/** The storefront id BOTH files report. They are two versions of one store, not two stores. */
const STOREFRONT_TYPE = 3

/**
 * Far enough out that the client never refetches — the same sentinel the capture carried. A real
 * storefront rotates; these are regenerated by hand, so they must not expire on their own.
 */
const NEXT_UPDATE = '2226-06-14T00:12:20.1324853Z'

/** One `Prices` / `SubscriberPrices` entry, in the shape the capture used. */
const priceEntry = (p: number) => [
	{ CurrencyType: CURRENCY_TYPE_TOKENS, Price: p, StorefrontSaleData: null, Type: 0 },
]

const build = new Command('build')
	.description('Generate sf3.json and sf3-2025.json from the item catalog')
	.action(async () => {
		const { avatarItems, skins } = await readCaptures()

		// The catalog ids come from the same loader the DB load uses, so the number in these files
		// is the number in the table. An avatar item's `item_key` IS its `AvatarItemDesc`, which is
		// what lets the two be matched up without a second numbering scheme to keep in step.
		const { rows } = buildCatalogLoad(avatarItems, skins)
		const kindAt = CATALOG_INSERT_COLUMNS.indexOf('kind')
		const catalogIdByDesc = new Map(
			rows.filter((r) => r.values[kindAt] === CatalogKind.AvatarItem).map((r) => [r.key, r.id])
		)

		// The items the catalog does not model — consumables and the random boxes. Carried across
		// verbatim; the catalog has no prices for these and does not model a box at all. They were
		// filtered when the file was cut, so nothing is re-checked here.
		const carried = JSON.parse(
			await fs.readFile(path.join(getRepoRoot(), CARRIED_ITEMS), 'utf8')
		) as Array<{ PurchasableItemId: number }>

		const byRarity = new Map<number, number>()
		const excluded = new Map<number, number>()
		const forSale = avatarItems.filter((item) => {
			if (isSellableRarity(item.Rarity)) return true
			excluded.set(item.Rarity, (excluded.get(item.Rarity) ?? 0) + 1)
			return false
		})

		const storeItems = forSale.map((item) => {
			const catalogId = catalogIdByDesc.get(item.AvatarItemDesc)
			if (catalogId === undefined) {
				throw new Error(`no catalog id for avatar item ${item.AvatarItemDesc}`)
			}
			const price = priceForRarity(item.Rarity)
			byRarity.set(item.Rarity, (byRarity.get(item.Rarity) ?? 0) + 1)
			return {
				// Key order and every constant field mirror the capture, because the client's parser
				// reads this shape and a store that differs from the one known to work is a needless
				// variable.
				GiftDrop: {
					AvatarItemDesc: item.AvatarItemDesc,
					AvatarItemType: item.AvatarItemType,
					ConsumableItemDesc: '',
					Context: 0,
					Currency: 0,
					CurrencyType: 0,
					EquipmentModificationGuid: '',
					EquipmentPrefabName: '',
					FriendlyName: item.FriendlyName,
					// The capture has GiftDropId === PurchasableItemId on all 1161 of its items.
					GiftDropId: catalogId,
					IsQuery: false,
					ItemSetFriendlyName: '',
					ItemSetId: 0,
					Rarity: item.Rarity,
					SubscribersOnly: false,
					// The catalog's tooltip is genuinely null on some rows; the client's field is a
					// string, so this is the one place the distinction is flattened.
					Tooltip: item.Tooltip ?? '',
					Unique: true,
				},
				IsFeatured: false,
				Prices: priceEntry(price),
				// The catalog id, directly — one number, no second numbering to keep in step. It is
				// already clear of every captured id (see `CATALOG_ID_BASE`), which is what lets the
				// carried items and these share a file.
				PurchasableItemId: catalogId,
				SubscriberPrices: priceEntry(subscriberPriceFor(price)),
				Type: 0,
				// Not emitted — only used to split the two files below.
				_createdAt: item.CreatedAt,
			}
		})

		const write = (file: string, items: typeof storeItems) => {
			const merged = [...carried, ...items.map(({ _createdAt, ...rest }) => rest)]
			// An id meaning two different items depending on which half answered first is the one
			// thing this merge must not do. Refused rather than resolved by ordering, since the whole
			// point of `CATALOG_ID_BASE` is that it cannot happen.
			const ids = merged.map((i) => i.PurchasableItemId)
			if (new Set(ids).size !== ids.length) {
				throw new Error(
					`${file}: duplicate PurchasableItemId across the carried and generated halves`
				)
			}
			const out = `${OUT_DIR}/${file}`
			writeFileSync(
				out,
				`${JSON.stringify(
					{
						NextUpdate: NEXT_UPDATE,
						StoreItems: merged,
						StorefrontType: STOREFRONT_TYPE,
						// Deliberately 0 — the discount is expressed ONLY in `SubscriberPrices`.
						// Announcing it again here risks a client taking the 10% off an already
						// discounted price and posting through the server's own subscriber floor,
						// refused as "Price has changed".
						SubscriberDiscountPercent: 0,
					},
					null,
					'\t'
				)}\n`
			)
			return { out, count: merged.length }
		}

		const legacy = storeItems.filter((i) => existedByLegacyBuild(i._createdAt))
		const sf3 = write('sf3.json', legacy)
		const sf32025 = write('sf3-2025.json', storeItems)

		const table = new Table({ head: ['rarity', 'items', 'price', 'subscriber'] })
		for (const rarity of [...byRarity.keys()].sort((a, b) => a - b)) {
			const price = priceForRarity(rarity)
			table.push([
				String(rarity),
				String(byRarity.get(rarity)),
				String(price),
				String(subscriberPriceFor(price)),
			])
		}
		console.log(table.toString())
		for (const [rarity, n] of [...excluded].sort((a, b) => a[0] - b[0])) {
			console.log(chalk.yellow(`excluded ${n} item(s) of rarity ${rarity} — not for sale`))
		}
		const undated = storeItems.filter((i) => i._createdAt === undefined).length
		if (undated > 0) {
			console.log(
				chalk.yellow(
					`${undated} item(s) carry no CreatedAt and are left out of sf3 — nothing shows they predate the cutoff`
				)
			)
		}
		console.log(
			chalk.green(
				`✓ ${sf3.out}: ${sf3.count} items ` +
					`(${carried.length} carried + ${legacy.length} created before ${LEGACY_CLIENT_BUILD_DATE})`
			)
		)
		console.log(
			chalk.green(
				`✓ ${sf32025.out}: ${sf32025.count} items ` +
					`(${carried.length} carried + ${storeItems.length} from the catalog)`
			)
		)
		console.log(
			`  build ${LEGACY_CLIENT_BUILD} and earlier is served sf3.json; later builds sf3-2025.json`
		)
	})

export const storefrontCmd = new Command('storefront')
	.description('Generate the storefront catalogs the econ worker serves')
	// Bare `storefront` (no subcommand) prints help and exits cleanly, rather than commander's
	// default "missing command" error (exit 1).
	.action((_opts, command: Command) => command.outputHelp())
	.addCommand(build)
	.addHelpText(
		'after',
		`
Both files are the general store at two points in time, generated from the item catalog and
served under storefront id 3. The econ worker picks which one a caller gets from their build:
sf3.json for ${LEGACY_CLIENT_BUILD} and earlier, sf3-2025.json for later.

The consumables and random boxes come from apps/econ/static/db/consumables.json — what survives
of the 2023 capture once its avatar items (the catalog has those) and its equipment skins
(awarded from weekly challenges, never sold) were dropped.

Regenerate whenever apps/econ/static/db/*.json changes, and after every \`runx catalog load\`:
a load renumbers catalog_id, and a stale file would list the wrong items.

Examples:
  $ runx storefront build`
	)
